# Generated by Django 5.2.8 on 2025-12-01 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkpoints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_skin_score', models.DecimalField(decimal_places=2, help_text='Calculated skin health score', max_digits=5)),
                ('improvement_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('insight_notes', models.TextField(blank=True, help_text='AI-generated or manual insights')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='checkpoints.dailycheckpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
                ('uv_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='checkpoints.uvreading')),
            ],
            options={
                'db_table': 'progress_record',
                'ordering': ['-timestamp'],
            },
        ),
    ]
