# Generated by Django 5.2.8 on 2025-12-01 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acne_level', models.IntegerField(default=0, help_text='Acne severity score (0-100)')),
                ('oil_level', models.IntegerField(default=0, help_text='Oil/sebum level (0-100)')),
                ('dark_spot_score', models.IntegerField(default=0, help_text='Dark spots/hyperpigmentation (0-100)')),
                ('redness_score', models.IntegerField(default=0, help_text='Redness/inflammation (0-100)')),
                ('hydration_score', models.IntegerField(default=0, help_text='Skin hydration level (0-100)')),
                ('texture_score', models.IntegerField(default=0, help_text='Skin texture quality (0-100)')),
                ('scan_image', models.ImageField(blank=True, null=True, upload_to='checkpoints/')),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_checkpoint',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UVReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv_index', models.DecimalField(decimal_places=2, help_text='UV Index value', max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Humidity percentage', max_digits=5)),
                ('pollution_level', models.IntegerField(default=0, help_text='Air quality index (0-500)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uv_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uv_reading',
                'ordering': ['-timestamp'],
            },
        ),
    ]
