# Generated by Django 5.2.8 on 2025-12-01 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkincareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('exfoliant', 'Exfoliant'), ('mask', 'Mask'), ('eye_cream', 'Eye Cream'), ('spot_treatment', 'Spot Treatment'), ('other', 'Other')], max_length=20)),
                ('ingredients', models.JSONField(default=list, help_text='List of ingredients')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skincare_product',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('am', 'Morning (AM)'), ('pm', 'Evening (PM)'), ('am_pm', 'Both AM & PM'), ('weekly', 'Weekly'), ('as_needed', 'As Needed')], default='pm', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if still using', null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='products.skincareproduct')),
            ],
            options={
                'db_table': 'product_usage',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='IngredientSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('caution', 'Use with Caution'), ('avoid', 'Avoid')], default='safe', max_length=10)),
                ('flagged_ingredients', models.JSONField(default=list, help_text='List of problematic ingredients')),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_checks', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='products.skincareproduct')),
            ],
            options={
                'db_table': 'ingredient_safety',
                'ordering': ['-checked_at'],
            },
        ),
    ]
